# Generated by Django 5.2.1 on 2025-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.JSONField(default=list),
        ),
    ]
