# Generated by Django 5.2.1 on 2025-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_color_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
