# Generated by Django 5.2.1 on 2025-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_name_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'User Sent'), ('Canceled', 'Admin Canceled'), ('Accepted', 'Payment Accepted'), ('Received', 'User Received')], default='Pending', max_length=11),
        ),
    ]
