# Generated by Django 5.2.1 on 2025-05-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_order_paymethod_alter_order_shippingmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
