# Generated by Django 5.2.1 on 2025-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MannualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
            ],
        ),
    ]
