# Generated by Django 5.2.1 on 2025-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_mannualpayment_bank_id_mannualpayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannualpayment',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
