# Generated by Django 5.2.1 on 2025-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_mannualpayment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannualpayment',
            name='public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
