# Generated by Django 5.2.1 on 2025-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='road',
            field=models.TextField(max_length=100),
        ),
    ]
