# Generated by Django 5.0.7 on 2025-05-06 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_trackingorder_resolved_order'),
        ('userrole', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictrict', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('road', models.TextField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='order.orderrequest')),
                ('resolved_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='order.resolvedorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
