# Generated by Django 5.2.1 on 2025-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0002_alter_address_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
