# Generated by Django 5.0.7 on 2025-05-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='order',
        ),
        migrations.RemoveField(
            model_name='address',
            name='resolved_order',
        ),
    ]
