# Generated by Django 5.0.7 on 2025-05-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0003_remove_address_order_remove_address_resolved_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='dictrict',
            new_name='district',
        ),
    ]
