# Generated by Django 5.2.1 on 2025-05-23 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0004_rename_dictrict_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be exactly 11 digits', regex='^\\d{11}$')]),
        ),
    ]
