# Generated by Django 5.2.1 on 2025-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0005_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
