# Generated by Django 5.2.1 on 2025-07-01 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userrole', '0003_alter_usermodel_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('us_tax', models.CharField(blank=True, default='8.87%', max_length=10, null=True)),
                ('us_tax_amount_in_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('us_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('dollar_rate', models.FloatField(blank=True, default=125.0, null=True)),
                ('bdt_total', models.IntegerField(blank=True, default=0.0, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=8.87, max_digits=10)),
                ('converted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_fee', models.IntegerField(default=0)),
                ('weight_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('box_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('platform_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('due', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(default='PD', max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automated_orders', to='userrole.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
