# Generated by Django 5.2.1 on 2025-07-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_automatedorder_converted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedorder',
            name='converted_price',
        ),
    ]
