# Generated by Django 5.2.1 on 2025-07-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_remove_automatedorder_converted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedorder',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='automatedorder',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='automatedorder',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
