# Generated by Django 5.2.1 on 2025-07-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_automatedorder_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedorder',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='automatedorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Payment Due'), ('due', 'Payment Due'), ('accepted', 'Payment Accepted'), ('delivered', 'Delivered')], default='due', max_length=10),
        ),
    ]
