# Generated by Django 5.2.1 on 2025-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_automatedorder_cost_alter_automatedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('accepted', 'Payment Accepted'), ('delivered', 'Delivered')], default='pending', max_length=15),
        ),
    ]
