# Generated by Django 5.2.1 on 2025-05-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userrole', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('is_box', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request', to='userrole.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolvedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=1000)),
                ('tracker', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('converted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_fee', models.IntegerField(default=0)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('platform_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.IntegerField()),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('CN', 'Canceled'), ('PD', 'Payment Done'), ('SP', 'Shipped'), ('UR', 'User Received')], default='AC', max_length=2)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order', to='userrole.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('is_shipped', models.BooleanField(default=False)),
                ('shipped_time', models.DateTimeField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('received_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_status', to='order.resolvedorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
