# Generated by Django 5.0.7 on 2025-04-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingorder',
            old_name='ResolvedOrder',
            new_name='resolved_order',
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('OC', 'Order Complete')], default='PD', max_length=2),
        ),
    ]
