# Generated by Django 5.0.7 on 2025-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_resolvedorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedorder',
            name='box_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
