# Generated by Django 5.2.1 on 2025-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderrequest_product_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingorder',
            old_name='shipped_time',
            new_name='canceled_time',
        ),
        migrations.RenameField(
            model_name='trackingorder',
            old_name='is_shipped',
            new_name='is_canceled',
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='is_landed_in_bd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='is_on_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='is_ready_to_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='is_shipped_in_usa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='landed_in_bd_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='on_board_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='ready_to_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='shipped_in_usa_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resolvedorder',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('CN', 'Canceled'), ('PD', 'Payment Done'), ('SB', 'Shipped in USA'), ('OB', 'On Board for BD'), ('LD', 'Landed in BD'), ('RD', 'Ready to Delivery'), ('UR', 'User Received')], default='AC', max_length=2),
        ),
    ]
