# Generated by Django 5.0.7 on 2025-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_trackingorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedorder',
            name='estimated_arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
