# Generated by Django 5.2.1 on 2025-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_shipped_time_trackingorder_canceled_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvedorder',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('CN', 'Canceled'), ('PD', 'Payment Done'), ('SP', 'Shipped in USA'), ('OB', 'On Board for BD'), ('LB', 'Landed in BD'), ('RD', 'Ready to Delivery'), ('UR', 'User Received')], default='AC', max_length=2),
        ),
    ]
