# Generated by Django 5.2.1 on 2025-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_resolvedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='product_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resolvedorder',
            name='product_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
