# Generated by Django 5.0.7 on 2025-05-03 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderrequest_is_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingorder',
            name='resolved_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_status', to='order.resolvedorder'),
        ),
    ]
