# Generated by Django 5.2.1 on 2025-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderrequest_product_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='from_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resolvedorder',
            name='from_us',
            field=models.BooleanField(default=False),
        ),
    ]
