# Generated by Django 5.0.7 on 2025-05-07 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_trackingorder_resolved_order'),
        ('userrole', '0003_remove_address_order_remove_address_resolved_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request', to='userrole.address'),
        ),
        migrations.AddField(
            model_name='resolvedorder',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order', to='userrole.address'),
        ),
    ]
