# Generated by Django 5.0.7 on 2025-05-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderrequest_address_resolvedorder_address'),
        ('userrole', '0003_remove_address_order_remove_address_resolved_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request', to='userrole.address'),
        ),
        migrations.AlterField(
            model_name='resolvedorder',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order', to='userrole.address'),
        ),
    ]
