# Generated by Django 5.2.1 on 2025-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderrequest_from_us_resolvedorder_from_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='from_us',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resolvedorder',
            name='from_us',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
