# Generated by Django 5.0.7 on 2025-05-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderrequest_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolvedorder',
            name='is_paid',
        ),
    ]
