# Generated by Django 5.2.1 on 2025-06-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderrequest_from_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingorder',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='refunded_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resolvedorder',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('CN', 'Canceled'), ('PD', 'Payment Done'), ('SP', 'Shipped in USA'), ('OB', 'On Board for BD'), ('LB', 'Landed in BD'), ('RD', 'Ready to Delivery'), ('RF', 'Refunded'), ('DD', 'Delivery Done')], default='AC', max_length=2),
        ),
    ]
