# Generated by Django 5.2.1 on 2025-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_trackingorder_is_refunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
