# Generated by Django 5.2.1 on 2025-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_resolvedorder_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvedorder',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('CN', 'Canceled'), ('PD', 'Payment Done'), ('SP', 'Shipped'), ('UR', 'User Received')], default='AC', max_length=2),
        ),
    ]
