# Generated by Django 5.2.1 on 2025-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderrequest_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedorder',
            name='weight_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
