# Generated by Django 5.2.1 on 2025-05-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_resolvedorder_payment_id_resolvedorder_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingorder',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingorder',
            name='shipped_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
