# Generated by Django 5.2.1 on 2025-05-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_trackingorder_paid_time_trackingorder_received_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvedorder',
            name='payment_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
