# Generated by Django 5.2.1 on 2025-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_resolvedorder_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedorder',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
