# Generated by Django 5.2.1 on 2025-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_resolvedorder_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedorder',
            name='platform_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
