# Generated by Django 5.2.1 on 2025-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_resolvedorder_platform_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='product_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resolvedorder',
            name='product_url',
            field=models.URLField(max_length=1000),
        ),
    ]
